"""
Django settings for freearkweb project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# 尝试加载环境变量
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # python_dotenv 未安装时直接使用系统环境变量，不影响运行
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境应当从环境变量中获取SECRET_KEY
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-i%ixus$z-threi-#e&(th%w$a4zi+oq=)-jz&)y!m((g#!iype')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'  # 默认关闭DEBUG模式

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.31.51,192.168.31.52,et116374mm892.vicp.fun').split(',')

# 生产环境安全设置
if not DEBUG:
    # 启用 HTTPS 设置
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
    SECURE_HSTS_SECONDS = 31536000  # 一年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 安全 Cookie 设置
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    
    # 防止点击劫持
    X_FRAME_OPTIONS = 'DENY'
    
    # 内容安全策略
    # 可以根据实际情况调整
    CSP_DEFAULT_SRC = ["'self'"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',  # Django Channels — WebSocket 支持（见 ADR-001）
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # v1.6.0 RBAC：拦截 user（业主）角色对业务 API 的访问（白名单外 /api/ 一律 403）
    'api.middleware.UserRoleApiGuardMiddleware',
]

ROOT_URLCONF = 'freearkweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freearkweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库配置 - 支持MySQL和SQLite切换
# 设置数据库切换开关：True使用SQLite，False使用MySQL
USE_SQLITE = False

# MySQL数据库配置
MYSQL_DATABASE = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'freeark',
    'USER': 'root',
    'PASSWORD': 'root',
    'HOST': '192.168.31.98',
    'PORT': '3306',
    'OPTIONS': {
        'charset': 'utf8mb4',
        'use_unicode': True,
        # 连接超时配置
        'connect_timeout': 60,  # 连接超时时间，单位秒
        'read_timeout': 60,     # 读取超时时间，单位秒
        'write_timeout': 60,    # 写入超时时间，单位秒
        'autocommit': True,     # 自动提交模式
    },
    # 连接池和会话配置
    'CONN_MAX_AGE': 300,  # 数据库连接的最大生存时间，单位秒
}

# SQLite数据库配置
SQLITE_DATABASE = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

# 根据开关选择数据库
# 当运行测试时（manage.py test），自动使用 SQLite 以避免依赖生产数据库
import sys as _sys
_RUNNING_TESTS = 'test' in _sys.argv
DATABASES = {
    'default': SQLITE_DATABASE if (USE_SQLITE or _RUNNING_TESTS) else MYSQL_DATABASE
}

# 缓存配置（perf-P0：看板接口短期缓存；perf-P2：切换至 Redis 后端，见 ADR-P2-001）
#
# 测试：DummyCache（无操作），避免 30s 缓存导致用例间数据陈旧/串扰。
#   _RUNNING_TESTS 分支不能动 Redis，确保 manage.py test 无需 redis-server。
#
# 生产：Django 内置 RedisCache（django.core.cache.backends.redis.RedisCache）。
#   - LOCATION db=1：与 channels_redis（db=0）隔离，避免键冲突。
#   - socket_connect_timeout/socket_timeout=1（OPTIONS 中传给 ConnectionPool）：
#     防止 Redis 慢响应（或未启动）拖垮 uvicorn worker 线程，最多 1s 放弃并触发
#     异常，由 cache_dashboard 装饰器的 try/except 兜底降级（非 500）。
#   - KEY_PREFIX='fa_cache'：键隔离前缀，便于 redis-cli 手工排查。
#   - TIMEOUT=30：默认 TTL 30s，与 P0 LocMemCache 策略一致。
#   - 降级策略：Django 内置 RedisCache 无 IGNORE_EXCEPTIONS，降级兜底在
#     cache_dashboard 装饰器的 try/except 层实现（见 api/views.py）。
#
# 回滚：将生产分支改回 LocMemCache（LOCATION='freeark-dashboard-cache'）即可，
#   Redis 服务和 channels_redis 不受影响，无需重启其他服务。
if _RUNNING_TESTS:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                # socket_connect_timeout/socket_timeout 由 redis-py ConnectionPool 解析
                # （ConnectionPool.from_url() 支持此参数，5.x/6.x 均有效）
                'socket_connect_timeout': 1,
                'socket_timeout': 1,
            },
            'KEY_PREFIX': 'fa_cache',
            'TIMEOUT': 30,
        }
    }

# 输出数据库配置信息用于调试
# 使用日志系统记录配置信息，避免直接print导致重复输出


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS配置 - 允许所有来源
# 更精确地配置CORS源，而不是允许所有源
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8080',
    'http://192.168.31.51',        # Nginx 80端口（LAN主要入口）
    'http://192.168.31.51:8000',
    'http://192.168.31.51:8080',
    'http://192.168.31.52',
    'http://192.168.31.52:8000',
    'http://192.168.31.52:8080',
    'http://et116374mm892.vicp.fun',  # 修正：mm892（原来少了一个m）
]
CORS_ALLOW_CREDENTIALS = True

# 允许前端使用credentials时的跨域请求
CORS_ALLOWED_ORIGINS_WITH_CREDENTIALS = True

# CSRF Cookie配置 - 确保跨域环境中cookie正常工作
# 根据是否为DEBUG模式设置不同的cookie策略
# HTTP 部署（无 HTTPS），Secure 必须为 False，否则浏览器丢弃 cookie
# 若将来启用 HTTPS，可将 CSRF_COOKIE_SECURE 改为 True，SAMESITE 改为 'None'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax 兼容同站及 Nginx 同源代理；None 需要 Secure=True
CSRF_COOKIE_HTTPONLY = False
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF信任源配置 - 允许本地环境、内网IP和花生壳域名
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8080',
    'http://192.168.31.51',        # Nginx 80端口
    'http://192.168.31.51:8000',
    'http://192.168.31.51:8080',
    'http://192.168.31.52',
    'http://192.168.31.52:8000',
    'http://192.168.31.52:8080',
    'http://et116374mm892.vicp.fun',  # 修正拼写
]

# 确保cookie在开发环境中正确设置
SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE
SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE

# 自定义用户模型配置
AUTH_USER_MODEL = 'api.CustomUser'

# REST Framework配置
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # REQ-AUTH-001 (v0.9.0): 替换为滑动窗口超时认证类
        'api.authentication.SlidingWindowTokenAuthentication',
        # BUG-CSRF: 移除 SessionAuthentication。本项目 API 走 Token 认证，
        # SessionAuthentication 仅在请求携带 session cookie 且无 Token 头时生效，
        # 其 enforce_csrf() 会强制校验 csrftoken cookie；会话超时重登录后该 cookie
        # 缺失即抛 "CSRF failed: CSRF cookie not set"。Django admin (/admin/) 由
        # Django 自身 SessionMiddleware+CsrfViewMiddleware 处理，不受此项影响。
        # 'rest_framework.authentication.SessionAuthentication',
    ],
}

# ===========================================================================
# 会话超时配置（v0.9.0, REQ-AUTH-001, REQ-NFR-AUTH-001）
# ===========================================================================
# 会话不活动超时阈值（秒）。默认 30 分钟 = 1800 秒。
# 通过环境变量 SESSION_INACTIVITY_TIMEOUT 可覆盖（整数，秒）。
SESSION_INACTIVITY_TIMEOUT = int(os.environ.get('SESSION_INACTIVITY_TIMEOUT', 1800))

# "7天内保持登录"勾选后的延长超时阈值（秒）。默认 7 天 = 604800 秒。
# 登录时 remember_me=True 会在 TokenActivity.extended_session 标记，
# 认证时改用此阈值替代 SESSION_INACTIVITY_TIMEOUT。
# 通过环境变量 SESSION_EXTENDED_TIMEOUT 可覆盖（整数，秒）。
SESSION_EXTENDED_TIMEOUT = int(os.environ.get('SESSION_EXTENDED_TIMEOUT', 604800))

# 活动时间写入 DB 的节流阈值（秒）。默认 5 分钟 = 300 秒。
# 同一 token 在此时间内的多次请求只触发一次 DB UPDATE。
# 须满足：ACTIVITY_THROTTLE_SECONDS < SESSION_INACTIVITY_TIMEOUT
# 通过环境变量 ACTIVITY_THROTTLE_SECONDS 可覆盖（整数，秒）。
ACTIVITY_THROTTLE_SECONDS = int(os.environ.get('ACTIVITY_THROTTLE_SECONDS', 300))

# 服务账号用户名列表（机器令牌）。这些账号豁免 SlidingWindowTokenAuthentication 的
# 不活跃超时——它们供后台 agent（如 energy-expert 经 energy-agent 令牌写设备参数）
# 长期低频调用，不应被「人类会话超时」判过期（否则写操作 401「会话已超时」）。
# 逗号分隔，通过环境变量 SERVICE_ACCOUNT_USERNAMES 可覆盖。
SERVICE_ACCOUNT_USERNAMES = [
    s.strip()
    for s in os.environ.get('SERVICE_ACCOUNT_USERNAMES', 'energy-agent').split(',')
    if s.strip()
]

# ===========================================================================
# 微信小程序配置（v1.8.0_miniprogram_owner_account，REQ-AUTH-002）
# ===========================================================================
# AppID 和 AppSecret 从 .env 注入（与 DEEPSEEK_API_KEY 相同机制），绝不入 git。
WECHAT_MINIAPP_APPID = os.environ.get('WECHAT_MINIAPP_APPID', '')
WECHAT_MINIAPP_SECRET = os.environ.get('WECHAT_MINIAPP_SECRET', '')

# ===========================================================================
# 媒体文件配置（v1.12.0, REQ-PROFILE-004）
# ===========================================================================
# 用户上传头像等媒体文件的存储根目录。
# MEDIA_URL 用于构造返回给前端的可访问 URL（绝对路径）。
# 生产环境：由 Nginx 代理 /media/ → MEDIA_ROOT。
# 开发环境：DEBUG=True 时由 Django static() helper 服务。
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / os.environ.get('MEDIA_ROOT', 'media')

# ===========================================================================
# 屏端 MQTT broker（v1.10.0_miniprogram_param_settings）
# ===========================================================================
# 小程序业主端直连厂端 broker 收发参数（DeviceWrite/DeviceStatusUpdate）。
# 这些连接参数经 /api/miniapp/device-settings/config/ 下发给已登录业主，
# 不硬编码进仓库源码（ADR-07）。凭据走 .env。
# ⚠️ 该 broker 为厂商共享云，admin/public 可读写全租户所有屏——客户端直连的
#    全租户越权风险已在需求 OQ-10 书面接受。
SCREEN_MQTT_PROTOCOL = os.environ.get('SCREEN_MQTT_PROTOCOL', 'wxs')
SCREEN_MQTT_HOST = os.environ.get('SCREEN_MQTT_HOST', 'www.ttqingjiao.site')
SCREEN_MQTT_PORT = int(os.environ.get('SCREEN_MQTT_PORT', '8084'))
SCREEN_MQTT_PATH = os.environ.get('SCREEN_MQTT_PATH', '/mqtt')
SCREEN_MQTT_USERNAME = os.environ.get('SCREEN_MQTT_USERNAME', 'admin')
SCREEN_MQTT_PASSWORD = os.environ.get('SCREEN_MQTT_PASSWORD', 'public')

# 静态文件配置
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ---------------------------------------------------------------------------
# Django Channels 配置（WebSocket 支持，见 ADR-001）
# ---------------------------------------------------------------------------
# 使用 InMemoryChannelLayer：单进程场景，无需 Redis
# 注意：Uvicorn 必须以 --workers 1 启动（InMemoryChannelLayer 不支持多进程）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# ---------------------------------------------------------------------------
# OpenClaw Gateway 集成配置已于 v1.7.0 退役移除
# （聊天唯一路径为进程内 LangGraph 直连 DeepSeek；OPENCLAW_* 配置项已废弃）
# ---------------------------------------------------------------------------

# 记忆隔离：每次对话注入的最近历史轮数（每轮含 user + assistant 各一条）
# ADR-010 方案 10-A，N=20 轮（40 条消息）
CHAT_HISTORY_INJECT_TURNS = int(os.environ.get('CHAT_HISTORY_INJECT_TURNS', 20))

# ---------------------------------------------------------------------------
# 聊天后端选择（LangGraph 替换 OpenClaw —— 阶段 A 影子接入开关）
# 见 agents/langgraph-poc/PHASE3_ROLLOUT.md
#   openclaw  （默认）—— 现状，经 OpenClaw Gateway WS RPC，零行为变化
#   langgraph         —— 进程内 LangGraph 多 agent 编排（api.langgraph_chat）
# 切换/回滚只需改本 env 并重启 worker；默认 openclaw 部署无需安装 langgraph 依赖。
CHAT_BACKEND = os.environ.get('CHAT_BACKEND', 'openclaw')

# LangGraph 编排配置（仅 CHAT_BACKEND=langgraph 时生效）
# DEEPSEEK_API_KEY 必须在生产 .env 中设置，绝不提交 git、绝不写入任何 HTTP 响应。
LANGGRAPH_USE_FAKE_LLM = os.environ.get('LANGGRAPH_USE_FAKE_LLM', 'False') == 'True'
LANGGRAPH_MODEL = os.environ.get('LANGGRAPH_MODEL', 'deepseek-v4-flash')
# 阶段 D：意图路由分类器模型（决策2，可用更轻模型控成本）。空=用 LANGGRAPH_MODEL；
# 设为更轻的模型名（如 flash-mini）则路由单独走轻模型。**路由分类器始终 temperature 0**
# （确定性分类，消除路由抖动，见 orchestrator._make_router_llm）。
LANGGRAPH_ROUTER_MODEL = os.environ.get('LANGGRAPH_ROUTER_MODEL', '')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1')
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
LANGGRAPH_LLM_TIMEOUT = int(os.environ.get('LANGGRAPH_LLM_TIMEOUT', '60'))
# P0-1：路由关键词短路。唯一无撞车关键词命中时，orchestrator._route 直接用关键词结果、
# 跳过 LLM 分类器（省 ~2s/条；零精度损失，依据见 api/langgraph_chat/routing_eval）。
# 置 'False' 一键回退到「恒走 LLM 分类器」。0 命中或 ≥2 命中（撞车/复合）仍走 LLM。
LANGGRAPH_ROUTER_KEYWORD_SHORTCIRCUIT = os.environ.get(
    'LANGGRAPH_ROUTER_KEYWORD_SHORTCIRCUIT', 'True') == 'True'
# P0-2：粘性路由。当前问题零信号（LLM 空 + 无关键词）时，承接上一轮专家而非盲目落
# DEFAULT，接住「那上个月呢」这类追问。仅作零信号兜底，不覆盖关键词/LLM 明确判断。
# 置 'False' 一键回退到「零信号恒落 DEFAULT_EXPERT」。
LANGGRAPH_ROUTER_STICKY = os.environ.get(
    'LANGGRAPH_ROUTER_STICKY', 'True') == 'True'
# P1-2：域外/闲聊路径。LLM 明确表态问题不属任何专家（且无关键词/粘性）时，路由到通用应答
# 节点（友好寒暄 + 引导能力介绍），而非盲目塞给能耗专家。置 'False' 回退到「域外恒落 DEFAULT」。
LANGGRAPH_ROUTER_OOD_PATH = os.environ.get(
    'LANGGRAPH_ROUTER_OOD_PATH', 'True') == 'True'
# P1-1：语义路由（关键词短路与 LLM 之间的高置信中间层，复用 RAG embedding）。
# **默认 False**：首次往路由热路径加远端 embedding 调用，保守默认关，灰度验证后再 env 开。
# 命中条件：查询对各专家范例的最大余弦 top ≥ TAU 且与次高 margin ≥ MARGIN（Phase-0 PoC 标定）。
# fail-open：embedding 不可用/异常 → 穿透 LLM 分类器（今天的行为）。
LANGGRAPH_ROUTER_SEMANTIC = os.environ.get(
    'LANGGRAPH_ROUTER_SEMANTIC', 'False') == 'True'
LANGGRAPH_ROUTER_SEM_TAU = float(os.environ.get('LANGGRAPH_ROUTER_SEM_TAU', '0.65'))
LANGGRAPH_ROUTER_SEM_MARGIN = float(os.environ.get('LANGGRAPH_ROUTER_SEM_MARGIN', '0.05'))
# P2-1：能力（工具）感知路由。CAPABILITY_PROMPT=True 时把各专家工具能力摘要注入路由 LLM
# 提示（预防把需某工具的问题分给无该工具的专家）。GUARD=True 保留确定性护栏
# _guard_against_misroute 作 backstop；能力提示验证充分后可置 False 退役护栏。
LANGGRAPH_ROUTER_CAPABILITY_PROMPT = os.environ.get(
    'LANGGRAPH_ROUTER_CAPABILITY_PROMPT', 'True') == 'True'
LANGGRAPH_ROUTER_GUARD = os.environ.get('LANGGRAPH_ROUTER_GUARD', 'True') == 'True'
# freeark-skill / agents 目录定位（默认仓内相对路径；Pi 上可经 env 指向真实路径）
LANGGRAPH_SKILL_DIR = os.environ.get('LANGGRAPH_SKILL_DIR', '')
LANGGRAPH_AGENTS_DIR = os.environ.get('LANGGRAPH_AGENTS_DIR', '')
# 阶段 B：工具调用模式 http（默认，经自身 REST）| direct（进程内直调 view，去自打 HTTP 一跳）
# 见 agents/langgraph-poc/PHASE3_ROLLOUT.md 阶段 B。改回 http 即回滚。
FA_TOOLS_MODE = os.environ.get('FA_TOOLS_MODE', 'http')

# 移除django-crontab配置，改用命令内置的定时功能
# 这些服务将在start_services.bat中直接启动

# ---------------------------------------------------------------------------
# 日志配置
# ---------------------------------------------------------------------------
# 日志目录优先级：
#   1. 环境变量 LOG_DIR（生产环境设置为 /home/pi/freeark-prod/logs/）
#   2. BASE_DIR/logs/（开发环境 fallback）
# 测试环境中 test_settings.py 会完全覆盖 LOGGING，不会触碰此目录。
# ---------------------------------------------------------------------------
_env_log_dir = os.environ.get('LOG_DIR', '')
if _env_log_dir:
    LOG_DIR = _env_log_dir
else:
    LOG_DIR = os.path.join(BASE_DIR, 'logs')

# 仅在非测试运行时创建目录（测试通过 test_settings.py 的 LOGGING 覆盖绕过文件 handler）
if not _RUNNING_TESTS:
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
    except OSError:
        # 目录创建失败时降级到用户主目录，不阻止启动
        LOG_DIR = os.path.join(os.path.expanduser('~'), 'freeark_logs')
        os.makedirs(LOG_DIR, exist_ok=True)

# 10 MB 单文件上限，保留 10 个滚动文件
_LOG_MAX_BYTES = 10 * 1024 * 1024
_LOG_BACKUP_COUNT = 10

# Django 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # 生产/文件格式：含时间戳、级别、模块名
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s %(process)d %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # 控制台格式：精简，开发阅读友好
        'simple': {
            'format': '%(asctime)s [%(levelname)-8s] %(name)s: %(message)s',
            'datefmt': '%H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # 主应用日志文件（INFO+，滚动）
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        # 控制台输出：仅 DEBUG 模式下生效（开发环境）
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        # 各后台服务的专属滚动日志文件
        'daily_usage_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'daily_usage_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'monthly_usage_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'monthly_usage_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'mqtt_consumer_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'mqtt_consumer_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'mqtt_consumer_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'mqtt_consumer.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'plc_cleanup_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'plc_cleanup_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'dph_cleanup_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'dph_cleanup_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
    },
    # root logger：生产默认 ERROR，设置 APP_LOG_LEVEL 环境变量可临时拉回 INFO 排障
    'root': {
        'handlers': ['file', 'console'],
        'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
    },
    'loggers': {
        # Django 框架日志（保留 WARNING 以便看到框架级警告）
        'django': {
            'handlers': ['file', 'console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # 应用整体（api.*）：生产默认 ERROR，APP_LOG_LEVEL 可 override
        'api': {
            'handlers': ['file', 'console'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # api.mqtt_consumer：默认 ERROR（US-A 已把高频成功日志降到 DEBUG）
        'api.mqtt_consumer': {
            'handlers': ['console', 'mqtt_consumer_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # api.mqtt_handlers：默认 ERROR（US-A 已把高频成功日志降到 DEBUG）
        'api.mqtt_handlers': {
            'handlers': ['console', 'mqtt_consumer_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # api.device_tree_sync 豁免（保留 WARNING，设备树同步频率低且失败重要）
        'api.device_tree_sync': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # 屏侧心跳消费豁免（保留 WARNING，连通性状态变化值得保留）
        'api.management.commands.screen_heartbeat_consumer': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # daily/monthly 用量任务豁免（每日/月一次，失败即异常）
        'daily_usage_service': {
            'handlers': ['console', 'daily_usage_service_log'],
            'level': 'WARNING',
            'propagate': False,
        },
        'monthly_usage_service': {
            'handlers': ['console', 'monthly_usage_service_log'],
            'level': 'WARNING',
            'propagate': False,
        },
        # MQTT consumer / PLC cleanup 后台服务：ERROR 即可
        'mqtt_consumer_service': {
            'handlers': ['console', 'mqtt_consumer_service_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'plc_cleanup_service': {
            'handlers': ['console', 'plc_cleanup_service_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # device_param_history 清理服务豁免：固定 INFO，
        # 清理结果（每批删除行数、最终累计、批次数）必须落盘可核查，
        # 不随生产 root 的 ERROR 默认值，否则清理是否成功无从验证
        'dph_cleanup_service': {
            'handlers': ['console', 'dph_cleanup_service_log'],
            'level': 'INFO',
            'propagate': False,
        },
        # PLC 连接监控豁免（设备上下线状态变化值得保留）
        'plc_connection_monitor': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'fix_daily_usage': {
            'handlers': ['file', 'console'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'fix_plc_data': {
            'handlers': ['file', 'console'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # RAG 服务（v1.4.0_sanheng_rag）：固定 INFO，入库进度需可查
        'api.rag_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api.views_rag': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ===========================================================================
# RAG 知识库配置（v1.4.0_sanheng_rag）
# ===========================================================================
# 安全约束：RAG_EMBEDDING_API_KEY 仅走 .env，绝不入 git/HTTP 响应/日志/前端。
# 凭据字段若为空，RAG 检索降级（fail-open）：聊天不报错，专家退回通用知识。
RAG_EMBEDDING_BASE_URL = os.environ.get('RAG_EMBEDDING_BASE_URL', '')
RAG_EMBEDDING_MODEL = os.environ.get('RAG_EMBEDDING_MODEL', 'BAAI/bge-m3')
RAG_EMBEDDING_API_KEY = os.environ.get('RAG_EMBEDDING_API_KEY', '')
# embedding 后端风格：'openai'（标准 /embeddings，支持批量）|
# 'doubao_multimodal'（火山方舟 doubao-embedding-vision 多模态 /embeddings/multimodal，逐条）
RAG_EMBEDDING_API_STYLE = os.environ.get('RAG_EMBEDDING_API_STYLE', 'openai')
RAG_TOP_K = int(os.environ.get('RAG_TOP_K', '5'))
RAG_SCORE_THRESHOLD = float(os.environ.get('RAG_SCORE_THRESHOLD', '0.3'))
RAG_CHUNK_SIZE = int(os.environ.get('RAG_CHUNK_SIZE', '500'))
RAG_CHUNK_OVERLAP = int(os.environ.get('RAG_CHUNK_OVERLAP', '50'))

# ===========================================================================
# v1.5.0 多模态提问：doubao-vision VLM 配置（MOD-MQ-07）
# ===========================================================================
# DOUBAO_VISION_MODEL：VLM 模型型号，默认 doubao-vision-lite；
# 可通过 .env 切换为 doubao-vision-pro-32k，不改代码（OQ-MQ-001 已决策）
DOUBAO_VISION_MODEL = os.environ.get('DOUBAO_VISION_MODEL', 'doubao-vision-lite-32k')

# DOUBAO_VISION_BASE_URL：火山方舟多模态接口端点
# 与 RAG embedding 共用账号/网络（已打通，无额外开通需求）
DOUBAO_VISION_BASE_URL = os.environ.get(
    'DOUBAO_VISION_BASE_URL', 'https://ark.cn-beijing.volces.com/api/v3')

# DOUBAO_API_KEY：豆包 API 密钥，与 RAG embedding 共用；
# 仅从 .env 读取，绝不入 git、HTTP 响应、日志、前端
DOUBAO_API_KEY = os.environ.get('DOUBAO_API_KEY', '')

# DOUBAO_VISION_TIMEOUT：单次 VLM 调用超时秒数
# doubao-vision-pro 推理偏慢 + Pi WiFi 偶发劣化，实测缩图后单次约 10s，但延迟方差大
# （同一 payload 偶尔 >30s）；配合 _downscale_for_vlm 缩图，默认 60s 留足余量（C-003）
DOUBAO_VISION_TIMEOUT = int(os.environ.get('DOUBAO_VISION_TIMEOUT', '60'))

# DOUBAO_VISION_MAX_RETRIES：超时/5xx 时最大重试次数
# 指数退避 2s 起始；4xx 不重试
DOUBAO_VISION_MAX_RETRIES = int(os.environ.get('DOUBAO_VISION_MAX_RETRIES', '1'))

# VISION_UPLOAD_TTL：临时图片存储 TTL 秒数（默认 10 分钟）
# TTL 到期后 get_upload 惰性清理，IMAGE_EXPIRED 错误引导用户重新上传
VISION_UPLOAD_TTL = int(os.environ.get('VISION_UPLOAD_TTL', '600'))

# VISION_UPLOAD_MAX_TOTAL_MB：进程内临时图片总占用上限（MB）
# 超过上限时 store_upload 抛 StorageCapacityError，预上传接口返回 503
VISION_UPLOAD_MAX_TOTAL_MB = int(os.environ.get('VISION_UPLOAD_MAX_TOTAL_MB', '50'))
# ===========================================================================
