"""
Django settings for freearkweb project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# 尝试加载环境变量
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # python_dotenv 未安装时直接使用系统环境变量，不影响运行
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境应当从环境变量中获取SECRET_KEY
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-i%ixus$z-threi-#e&(th%w$a4zi+oq=)-jz&)y!m((g#!iype')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'  # 默认关闭DEBUG模式

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.31.51,192.168.31.52,et116374mm892.vicp.fun').split(',')

# 生产环境安全设置
if not DEBUG:
    # 启用 HTTPS 设置
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
    SECURE_HSTS_SECONDS = 31536000  # 一年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 安全 Cookie 设置
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    
    # 防止点击劫持
    X_FRAME_OPTIONS = 'DENY'
    
    # 内容安全策略
    # 可以根据实际情况调整
    CSP_DEFAULT_SRC = ["'self'"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',  # Django Channels — WebSocket 支持（见 ADR-001）
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'freearkweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freearkweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库配置 - 支持MySQL和SQLite切换
# 设置数据库切换开关：True使用SQLite，False使用MySQL
USE_SQLITE = False

# MySQL数据库配置
MYSQL_DATABASE = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'freeark',
    'USER': 'root',
    'PASSWORD': 'root',
    'HOST': '192.168.31.98',
    'PORT': '3306',
    'OPTIONS': {
        'charset': 'utf8mb4',
        'use_unicode': True,
        # 连接超时配置
        'connect_timeout': 60,  # 连接超时时间，单位秒
        'read_timeout': 60,     # 读取超时时间，单位秒
        'write_timeout': 60,    # 写入超时时间，单位秒
        'autocommit': True,     # 自动提交模式
    },
    # 连接池和会话配置
    'CONN_MAX_AGE': 300,  # 数据库连接的最大生存时间，单位秒
}

# SQLite数据库配置
SQLITE_DATABASE = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

# 根据开关选择数据库
# 当运行测试时（manage.py test），自动使用 SQLite 以避免依赖生产数据库
import sys as _sys
_RUNNING_TESTS = 'test' in _sys.argv
DATABASES = {
    'default': SQLITE_DATABASE if (USE_SQLITE or _RUNNING_TESTS) else MYSQL_DATABASE
}

# 输出数据库配置信息用于调试
# 使用日志系统记录配置信息，避免直接print导致重复输出


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS配置 - 允许所有来源
# 更精确地配置CORS源，而不是允许所有源
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8080',
    'http://192.168.31.51',        # Nginx 80端口（LAN主要入口）
    'http://192.168.31.51:8000',
    'http://192.168.31.51:8080',
    'http://192.168.31.52',
    'http://192.168.31.52:8000',
    'http://192.168.31.52:8080',
    'http://et116374mm892.vicp.fun',  # 修正：mm892（原来少了一个m）
]
CORS_ALLOW_CREDENTIALS = True

# 允许前端使用credentials时的跨域请求
CORS_ALLOWED_ORIGINS_WITH_CREDENTIALS = True

# CSRF Cookie配置 - 确保跨域环境中cookie正常工作
# 根据是否为DEBUG模式设置不同的cookie策略
# HTTP 部署（无 HTTPS），Secure 必须为 False，否则浏览器丢弃 cookie
# 若将来启用 HTTPS，可将 CSRF_COOKIE_SECURE 改为 True，SAMESITE 改为 'None'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax 兼容同站及 Nginx 同源代理；None 需要 Secure=True
CSRF_COOKIE_HTTPONLY = False
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF信任源配置 - 允许本地环境、内网IP和花生壳域名
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8080',
    'http://192.168.31.51',        # Nginx 80端口
    'http://192.168.31.51:8000',
    'http://192.168.31.51:8080',
    'http://192.168.31.52',
    'http://192.168.31.52:8000',
    'http://192.168.31.52:8080',
    'http://et116374mm892.vicp.fun',  # 修正拼写
]

# 确保cookie在开发环境中正确设置
SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE
SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE

# 自定义用户模型配置
AUTH_USER_MODEL = 'api.CustomUser'

# REST Framework配置
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # REQ-AUTH-001 (v0.9.0): 替换为滑动窗口超时认证类
        'api.authentication.SlidingWindowTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# ===========================================================================
# 会话超时配置（v0.9.0, REQ-AUTH-001, REQ-NFR-AUTH-001）
# ===========================================================================
# 会话不活动超时阈值（秒）。默认 30 分钟 = 1800 秒。
# 通过环境变量 SESSION_INACTIVITY_TIMEOUT 可覆盖（整数，秒）。
SESSION_INACTIVITY_TIMEOUT = int(os.environ.get('SESSION_INACTIVITY_TIMEOUT', 1800))

# 活动时间写入 DB 的节流阈值（秒）。默认 5 分钟 = 300 秒。
# 同一 token 在此时间内的多次请求只触发一次 DB UPDATE。
# 须满足：ACTIVITY_THROTTLE_SECONDS < SESSION_INACTIVITY_TIMEOUT
# 通过环境变量 ACTIVITY_THROTTLE_SECONDS 可覆盖（整数，秒）。
ACTIVITY_THROTTLE_SECONDS = int(os.environ.get('ACTIVITY_THROTTLE_SECONDS', 300))

# 静态文件配置
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ---------------------------------------------------------------------------
# Django Channels 配置（WebSocket 支持，见 ADR-001）
# ---------------------------------------------------------------------------
# 使用 InMemoryChannelLayer：单进程场景，无需 Redis
# 注意：Uvicorn 必须以 --workers 1 启动（InMemoryChannelLayer 不支持多进程）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# ---------------------------------------------------------------------------
# OpenClaw Gateway 集成配置（见 ADR-002 v1.2，REQ-FUNC-005，REQ-NFR-004）
# ---------------------------------------------------------------------------
# 协议：WebSocket Gateway RPC（protocol v4），由 openclaw_adapter.py 实现
# 路径：'/' 是 OpenClaw Gateway 的唯一 WS 端点；http(s):// 会被适配层升级为 ws(s)://
# 安全约束：
#   OPENCLAW_GATEWAY_TOKEN 必须在生产服务器的 .env 文件中设置（不提交 git）
#   该 token 仅在服务端使用，绝不写入前端代码或任何 HTTP 响应
# 本地开发测试：在 FreeArkWeb/backend/freearkweb/.env 中设置
OPENCLAW_BASE_URL = os.environ.get('OPENCLAW_BASE_URL', 'http://127.0.0.1:18789')
OPENCLAW_GATEWAY_TOKEN = os.environ.get('OPENCLAW_GATEWAY_TOKEN', '')  # 必填，生产强 token
OPENCLAW_TIMEOUT = int(os.environ.get('OPENCLAW_TIMEOUT', '60'))         # 总流响应超时（秒）
OPENCLAW_CONNECT_TIMEOUT = int(os.environ.get('OPENCLAW_CONNECT_TIMEOUT', '10'))  # WS 升级 + 握手超时
# reasoning_effort：控制 DeepSeek v4-flash 的推理深度（low/medium/high），空字符串=使用模型默认值
# 实际值由 devops 在生产 .env 中写入，此处仅读取；代码层不硬编码
# 需求引用：REQ-FUNC-012，ADR-008（adapter 侧透传方案 A）
OPENCLAW_REASONING_EFFORT = os.environ.get('OPENCLAW_REASONING_EFFORT', '')

# 记忆隔离：每次对话注入的最近历史轮数（每轮含 user + assistant 各一条）
# ADR-010 方案 10-A，N=20 轮（40 条消息）
CHAT_HISTORY_INJECT_TURNS = int(os.environ.get('CHAT_HISTORY_INJECT_TURNS', 20))

# 移除django-crontab配置，改用命令内置的定时功能
# 这些服务将在start_services.bat中直接启动

# ---------------------------------------------------------------------------
# 日志配置
# ---------------------------------------------------------------------------
# 日志目录优先级：
#   1. 环境变量 LOG_DIR（生产环境设置为 /home/pi/freeark-prod/logs/）
#   2. BASE_DIR/logs/（开发环境 fallback）
# 测试环境中 test_settings.py 会完全覆盖 LOGGING，不会触碰此目录。
# ---------------------------------------------------------------------------
_env_log_dir = os.environ.get('LOG_DIR', '')
if _env_log_dir:
    LOG_DIR = _env_log_dir
else:
    LOG_DIR = os.path.join(BASE_DIR, 'logs')

# 仅在非测试运行时创建目录（测试通过 test_settings.py 的 LOGGING 覆盖绕过文件 handler）
if not _RUNNING_TESTS:
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
    except OSError:
        # 目录创建失败时降级到用户主目录，不阻止启动
        LOG_DIR = os.path.join(os.path.expanduser('~'), 'freeark_logs')
        os.makedirs(LOG_DIR, exist_ok=True)

# 10 MB 单文件上限，保留 10 个滚动文件
_LOG_MAX_BYTES = 10 * 1024 * 1024
_LOG_BACKUP_COUNT = 10

# Django 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # 生产/文件格式：含时间戳、级别、模块名
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s %(process)d %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # 控制台格式：精简，开发阅读友好
        'simple': {
            'format': '%(asctime)s [%(levelname)-8s] %(name)s: %(message)s',
            'datefmt': '%H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # 主应用日志文件（INFO+，滚动）
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        # 控制台输出：仅 DEBUG 模式下生效（开发环境）
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        # 各后台服务的专属滚动日志文件
        'daily_usage_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'daily_usage_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'monthly_usage_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'monthly_usage_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'mqtt_consumer_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'mqtt_consumer_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'mqtt_consumer_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'mqtt_consumer.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'plc_cleanup_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'plc_cleanup_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
        'dph_cleanup_service_log': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'dph_cleanup_service.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'maxBytes': _LOG_MAX_BYTES,
            'backupCount': _LOG_BACKUP_COUNT,
            'delay': True,
        },
    },
    # root logger：生产默认 ERROR，设置 APP_LOG_LEVEL 环境变量可临时拉回 INFO 排障
    'root': {
        'handlers': ['file', 'console'],
        'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
    },
    'loggers': {
        # Django 框架日志（保留 WARNING 以便看到框架级警告）
        'django': {
            'handlers': ['file', 'console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # 应用整体（api.*）：生产默认 ERROR，APP_LOG_LEVEL 可 override
        'api': {
            'handlers': ['file', 'console'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # api.mqtt_consumer：默认 ERROR（US-A 已把高频成功日志降到 DEBUG）
        'api.mqtt_consumer': {
            'handlers': ['console', 'mqtt_consumer_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # api.mqtt_handlers：默认 ERROR（US-A 已把高频成功日志降到 DEBUG）
        'api.mqtt_handlers': {
            'handlers': ['console', 'mqtt_consumer_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # api.device_tree_sync 豁免（保留 WARNING，设备树同步频率低且失败重要）
        'api.device_tree_sync': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # 屏侧心跳消费豁免（保留 WARNING，连通性状态变化值得保留）
        'api.management.commands.screen_heartbeat_consumer': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # daily/monthly 用量任务豁免（每日/月一次，失败即异常）
        'daily_usage_service': {
            'handlers': ['console', 'daily_usage_service_log'],
            'level': 'WARNING',
            'propagate': False,
        },
        'monthly_usage_service': {
            'handlers': ['console', 'monthly_usage_service_log'],
            'level': 'WARNING',
            'propagate': False,
        },
        # MQTT consumer / PLC cleanup 后台服务：ERROR 即可
        'mqtt_consumer_service': {
            'handlers': ['console', 'mqtt_consumer_service_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'plc_cleanup_service': {
            'handlers': ['console', 'plc_cleanup_service_log'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        # device_param_history 清理服务豁免：固定 INFO，
        # 清理结果（每批删除行数、最终累计、批次数）必须落盘可核查，
        # 不随生产 root 的 ERROR 默认值，否则清理是否成功无从验证
        'dph_cleanup_service': {
            'handlers': ['console', 'dph_cleanup_service_log'],
            'level': 'INFO',
            'propagate': False,
        },
        # PLC 连接监控豁免（设备上下线状态变化值得保留）
        'plc_connection_monitor': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'fix_daily_usage': {
            'handlers': ['file', 'console'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'fix_plc_data': {
            'handlers': ['file', 'console'],
            'level': os.getenv('APP_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
    },
}
