# Generated by Django 5.2.7 on 2025-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagequantitydaily',
            name='final_energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='末期能耗(kWh)'),
        ),
        migrations.AlterField(
            model_name='usagequantitydaily',
            name='usage_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='使用量(kWh)'),
        ),
    ]
