# Generated by Django 5.2.7 on 2025-10-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
