# Generated by Django 5.2.7 on 2025-11-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usagequantitydaily',
            name='final_energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='末期能耗(kWh)'),
        ),
        migrations.AlterField(
            model_name='usagequantitydaily',
            name='usage_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='使用量(kWh)'),
        ),
    ]
