# Generated by Django 5.2.7 on 2025-10-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_datapoint_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageQuantityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_part', models.CharField(max_length=20, verbose_name='专有部分')),
                ('building', models.CharField(max_length=10, verbose_name='楼栋')),
                ('unit', models.CharField(max_length=10, verbose_name='单元')),
                ('room_number', models.CharField(max_length=10, verbose_name='房号')),
                ('energy_mode', models.CharField(choices=[('制冷', '制冷'), ('制热', '制热')], max_length=10, verbose_name='供能模式')),
                ('initial_energy', models.IntegerField(verbose_name='初期能耗(kWh)')),
                ('final_energy', models.IntegerField(verbose_name='末期能耗(kWh)')),
                ('usage_quantity', models.IntegerField(verbose_name='使用量(kWh)')),
                ('time_period', models.DateField(verbose_name='时间段')),
            ],
            options={
                'verbose_name': '每日用量数据',
                'verbose_name_plural': '每日用量数据',
                'db_table': 'usage_quantity_daily',
            },
        ),
    ]
