# Generated by Django 5.2.7 on 2025-11-03 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plcdata_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcdata',
            name='usage_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='计量日期'),
        ),
    ]
