# Generated by Django 5.2.7 on 2025-11-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usagequantitydaily_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plcdata',
            index=models.Index(fields=['usage_date'], name='plc_data_usage_d_d062f1_idx'),
        ),
        migrations.AddIndex(
            model_name='plcdata',
            index=models.Index(fields=['specific_part'], name='plc_data_specifi_cc5988_idx'),
        ),
        migrations.AddIndex(
            model_name='plcdata',
            index=models.Index(fields=['energy_mode'], name='plc_data_energy__955bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='plcdata',
            index=models.Index(fields=['updated_at'], name='plc_data_updated_572ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='plcdata',
            index=models.Index(fields=['usage_date', 'specific_part', 'energy_mode'], name='plc_data_usage_d_838d74_idx'),
        ),
        migrations.AddIndex(
            model_name='plcdata',
            index=models.Index(fields=['usage_date', 'specific_part', 'energy_mode', 'updated_at'], name='plc_data_usage_d_574f93_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequantitydaily',
            index=models.Index(fields=['time_period'], name='usage_quant_time_pe_4d575c_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequantitydaily',
            index=models.Index(fields=['specific_part'], name='usage_quant_specifi_1ae188_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequantitydaily',
            index=models.Index(fields=['energy_mode'], name='usage_quant_energy__19bc89_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequantitydaily',
            index=models.Index(fields=['time_period', 'specific_part', 'energy_mode'], name='usage_quant_time_pe_7ed4d1_idx'),
        ),
    ]
