# Generated by Django 5.2.7 on 2025-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plcdata_plc_data_usage_d_d062f1_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usagequantitymonthly',
            index=models.Index(fields=['energy_mode'], name='usage_quant_energy__cd5fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequantitymonthly',
            index=models.Index(fields=['updated_at'], name='usage_quant_updated_acbd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='usagequantitymonthly',
            index=models.Index(fields=['specific_part', 'energy_mode', 'usage_month'], name='usage_quant_specifi_5a2a37_idx'),
        ),
    ]
