# Generated by Django 5.2.7 on 2025-11-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usagequantitymonthly_usage_quant_energy__cd5fd3_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plcdata',
            unique_together={('specific_part', 'energy_mode', 'usage_date')},
        ),
    ]
