# Generated by Django 5.2.7 on 2025-11-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_plcdata_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usagequantitydaily',
            index=models.Index(fields=['time_period', 'energy_mode'], name='usage_quant_time_pe_9707eb_idx'),
        ),
    ]
