# Generated by Django 5.2.7 on 2026-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usagequantitydaily_usage_quant_time_pe_9707eb_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_part', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='专有部分')),
                ('connection_status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=10, verbose_name='连接状态')),
                ('last_online_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次在线时间')),
                ('building', models.CharField(db_index=True, max_length=10, verbose_name='楼栋')),
                ('unit', models.CharField(db_index=True, max_length=10, verbose_name='单元')),
                ('room_number', models.CharField(db_index=True, max_length=10, verbose_name='房号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': 'PLC连接状态',
                'verbose_name_plural': 'PLC连接状态',
                'db_table': 'plc_connection_status',
                'indexes': [models.Index(fields=['connection_status'], name='plc_connect_connect_63f1e0_idx'), models.Index(fields=['building'], name='plc_connect_buildin_f4e61b_idx'), models.Index(fields=['unit'], name='plc_connect_unit_fc1f33_idx'), models.Index(fields=['last_online_time'], name='plc_connect_last_on_552960_idx'), models.Index(fields=['updated_at'], name='plc_connect_updated_e5b498_idx'), models.Index(fields=['building', 'unit'], name='plc_connect_buildin_30a13e_idx'), models.Index(fields=['connection_status', 'building', 'unit'], name='plc_connect_connect_1fb88d_idx')],
            },
        ),
    ]
