# Generated by Django 5.2.7 on 2026-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plcconnectionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCStatusChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_part', models.CharField(db_index=True, max_length=20, verbose_name='专有部分')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '离线')], max_length=10, verbose_name='状态变化类型')),
                ('change_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='状态变化时间')),
                ('building', models.CharField(db_index=True, default='', max_length=10, verbose_name='楼栋')),
                ('unit', models.CharField(db_index=True, default='', max_length=10, verbose_name='单元')),
                ('room_number', models.CharField(db_index=True, default='', max_length=10, verbose_name='房号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': 'PLC状态变化历史',
                'verbose_name_plural': 'PLC状态变化历史',
                'db_table': 'plc_status_change_history',
                'indexes': [models.Index(fields=['specific_part'], name='plc_status__specifi_badaaa_idx'), models.Index(fields=['status'], name='plc_status__status_88818a_idx'), models.Index(fields=['change_time'], name='plc_status__change__4c83ad_idx'), models.Index(fields=['building'], name='plc_status__buildin_62ad5f_idx'), models.Index(fields=['unit'], name='plc_status__unit_7e7e2b_idx'), models.Index(fields=['specific_part', 'change_time'], name='plc_status__specifi_844f24_idx'), models.Index(fields=['building', 'unit', 'change_time'], name='plc_status__buildin_ee577a_idx'), models.Index(fields=['status', 'change_time'], name='plc_status__status_2c1f59_idx')],
            },
        ),
    ]
