# Generated by Django 5.2.7 on 2026-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_plcstatuschangehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificPartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenMAC', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='屏幕MAC地址')),
                ('specific_part', models.CharField(db_index=True, max_length=20, verbose_name='专有部分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': '专有部分信息',
                'verbose_name_plural': '专有部分信息',
                'db_table': 'specific_part_info',
                'indexes': [models.Index(fields=['screenMAC'], name='specific_pa_screenM_fe6ff1_idx'), models.Index(fields=['specific_part'], name='specific_pa_specifi_a061ad_idx'), models.Index(fields=['screenMAC', 'specific_part'], name='specific_pa_screenM_3677ed_idx')],
            },
        ),
    ]
