# Generated by Django 6.0.6 on 2026-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_customuser_avatar_url_nickname'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceattrbinding',
            new_name='device_attr_device__30aac2_idx',
            old_name='dab_device_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceattrbinding',
            new_name='device_attr_attr_de_d49b67_idx',
            old_name='dab_attr_def_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceattrdef',
            new_name='device_attr_product_b9a8af_idx',
            old_name='dad_product_code_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceattrdef',
            new_name='device_attr_attr_ta_d80c10_idx',
            old_name='dad_attr_tag_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefloor',
            new_name='device_floo_owner_i_e5dc56_idx',
            old_name='df_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='devicenode',
            new_name='device_node_room_id_40afa1_idx',
            old_name='dn_room_idx',
        ),
        migrations.RenameIndex(
            model_name='devicenode',
            new_name='device_node_device__f6f23b_idx',
            old_name='dn_device_sn_idx',
        ),
        migrations.RenameIndex(
            model_name='devicenode',
            new_name='device_node_product_8527ca_idx',
            old_name='dn_product_code_idx',
        ),
        migrations.RenameIndex(
            model_name='devicenode',
            new_name='device_node_related_512d69_idx',
            old_name='dn_related_sn_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceroom',
            new_name='device_room_floor_i_358623_idx',
            old_name='dr_floor_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceroom',
            new_name='device_room_room_ty_a6eec1_idx',
            old_name='dr_room_type_idx',
        ),
        migrations.RenameIndex(
            model_name='plclatestdata',
            new_name='plc_latest__specifi_095900_idx',
            old_name='plc_latest__specifi_idx',
        ),
        migrations.RenameIndex(
            model_name='plclatestdata',
            new_name='plc_latest__param_n_78f8d3_idx',
            old_name='plc_latest__param_n_idx',
        ),
        migrations.RenameIndex(
            model_name='plclatestdata',
            new_name='plc_latest__specifi_0aa1e7_idx',
            old_name='plc_latest__sp_pn_idx',
        ),
        migrations.RenameIndex(
            model_name='plclatestdata',
            new_name='plc_latest__collect_7dac0c_idx',
            old_name='plc_latest__collect_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='persona',
            field=models.JSONField(blank=True, default=dict, help_text='{"greeting_style": "副官", "tone_style": "尊敬的舰长大人"}', verbose_name='人格偏好'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='owneruserbinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plclatestdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ragimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wechatbinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
