# Generated by Django 5.1.15 on 2026-08-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_fix_humidification_limit_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjutant_enabled', models.BooleanField(default=False, verbose_name='启用小程序副官')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应用功能配置',
                'verbose_name_plural': '应用功能配置',
                'db_table': 'app_feature_config',
            },
        ),
    ]
