version: '3.8'

services:
  # PostgreSQL数据库服务
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=freearkweb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d freearkweb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django后端服务
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=False
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=freearkweb
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-i%ixus$z-threi-#e&(th%w$a4zi+oq=)-jz&)y!m((g#!iype
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://localhost
      - CREATE_SUPERUSER=True
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # Vue前端服务
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: